# indexes.conf
# Defines the nginx index on the Splunk Indexer.
# Location: /opt/splunk/etc/system/local/indexes.conf
# Note: This can also be created via Splunk Web UI:
#       Settings → Indexes → New Index → Name: nginx

[nginx]
homePath   = $SPLUNK_DB/nginx/db
coldPath   = $SPLUNK_DB/nginx/colddb
thawedPath = $SPLUNK_DB/nginx/thaweddb
maxTotalDataSizeMB = 5120
frozenTimePeriodInSecs = 2592000    # 30 days retention